# Usa una imagen base de .NET
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Usa una imagen de desarrollo para construir el proyecto
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Gym/Gym.csproj", "Gym/"]
RUN dotnet restore "Gym/Gym.csproj"
COPY . .
WORKDIR "/src/Gym"
RUN dotnet build "Gym.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Gym.csproj" -c Release -o /app/publish

# Copia los archivos al contenedor
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gym.dll"]
